// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsvuxmcykpbzvvpzjqvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzdnV4bWN5a3BienZ2cHpqcXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTkyODMsImV4cCI6MjA2NTg5NTI4M30.O66DBMoAu6T59BoYzXB47jhJCTytsWwPV9Asz3O7zPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);